global:

      save_results: True

      save_directory: "./results/"

      frequency:
            f_scale: "log10"
            f_min: 1e-5 
            f_max: 1
            N_fbins: 500



population:

      population_name: "mock_catalogue"
      
      population_import_name: "simple_single_Z_import"

      population_path: "./data/populations/Initials_SeBa_Gamma175Alpha4_Z02.txt"

      considered_source: "white_dwarf"

      total_population_mass: 4e6      # BH 2.592e5



cosmology:

      # using standard cosmology or custom
      standard: True

      # included cosmologies are: Planck18, Planck15, Planck13, WMAP9, WMAP7, WMAP5, WMAP3, WMAP1 
      standard_cosmology: "Planck18"

      # custom cosmologies should named as in the astropy.cosmology module. e.g., from DESI+CMB+DESY5 table V of https://arxiv.org/pdf/2503.14738
      custom_cosmology: 
          cosmology_type: "w0waCDM"
          params:
              H0:        66.74
              Om0:       0.3191
              Ode0:      0.6809
              w0:        -0.752
              wa:        -0.86

      z_scale: "log10"

      z_power_scale: null

      z_min: 1e-4

      z_max: 8                # max value is 10

      N_zbins: 20



SFH:

      # currently "madau_and_dickinson", "madau_and_fragos", "strolger", and "chruslinska_and_nelemans" are implemented
      SFH_name: "madau_and_dickinson"

      SFH_path: "./data/SFRDs/moderate_FOH_z_dM.dat"

      SFH_metallicities: [0.0001, 0.001, 0.005, 0.01, 0.02, 0.03] # 0.02 

      SFH_metallicity_bins: [0, 0.0005, 0.003, 0.008, 0.015, 0.03, 0.1] # min=0, max=?
