name: Install and Test Package

on: [push]

jobs:
  validate-package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install package and dependencies
      run: uv sync --locked --all-extras --dev

    - name: Run tests folder
      run: uv run pytest tests/